// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for project documents */
interface ProjectDocumentData {
  /**
   * Slice Zone field in *project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField;
  /**
   * Meta Image field in *project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *project → Slice Zone*
 *
 */
type ProjectDocumentDataSlicesSlice = ProjectSliceSlice;
/**
 * project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;
export type AllDocumentTypes = ProjectDocument;
/**
 * Primary content in ProjectSlice → Primary
 *
 */
interface ProjectSliceSliceDefaultPrimary {
  /**
   * Client field in *ProjectSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.primary.client
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  client: prismic.RichTextField;
  /**
   * Project Name field in *ProjectSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.primary.project_name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  project_name: prismic.RichTextField;
  /**
   * Date field in *ProjectSlice → Primary*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.primary.date
   * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
   *
   */
  date: prismic.TimestampField;
  /**
   * Description field in *ProjectSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Video field in *ProjectSlice → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.primary.video
   * - **Documentation**: https://prismic.io/docs/core-concepts/embed
   *
   */
  video: prismic.EmbedField;
}
/**
 * Default variation for ProjectSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectSliceSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *ProjectSlice*
 *
 */
type ProjectSliceSliceVariation = ProjectSliceSliceDefault;
/**
 * ProjectSlice Shared Slice
 *
 * - **API ID**: `project_slice`
 * - **Description**: `ProjectSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectSliceSlice = prismic.SharedSlice<
  "project_slice",
  ProjectSliceSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      ProjectDocument,
      AllDocumentTypes,
      ProjectSliceSliceDefaultPrimary,
      ProjectSliceSliceDefault,
      ProjectSliceSliceVariation,
      ProjectSliceSlice,
    };
  }
}
